language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.18"
  - "5.20"
env:
  - PERL5LIB=/usr/share/perl5/
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libbio-perl-perl
install:
    - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls
    - cpanm --quiet --installdeps .
script: 
    - perl Makefile.PL
    - make
    - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrv
    - cover
after_success:
    - cover -report coveralls
