language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.18"
  - "5.20"
sudo:
  false
addons:
  apt:
    packages:
    - bioperl
    - bioperl-run
env:
    - PERL5LIB=/usr/share/perl5/
install:
    - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls
    - cpanm --quiet --installdeps .
    - wget 'http://www.bx.psu.edu/~rsharris/lastz/newer/lastz-1.03.73.tar.gz'
    - tar xzf lastz-1.03.73.tar.gz
    - cd lastz-distrib-1.03.73
    - make
    - cd ..
    - export PATH="$PATH":lastz-distrib-1.03.73/src/
script: 
    - perl Makefile.PL
    - make
    - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrv
    - cover
after_success:
    - cover -report coveralls
notifications:
  slack:
    secure: mVaMpDsacnCsBtl50EjX87CGoyyg4oDY5wbqIjMLnFkGWSQFPoBy3dnby0q1RfZrnSceUwhCOZ/XVUWA+kdNU0NNKBPnp7W3PSGwoTqz3BHz6BXdTiCzEhUmQHyLneH5rBH6jx13ta02vmz8T8j4IAyEkCUpBo31p1ZKlIGFiP6IyE17VkhnTJg6Oa9cVNODgJsUf3fHiqESXrqwxvwzU/izK99hMnxPfLeYtenX/UWO/r5kFWXPthl5npjcbzditOTFHq+2TnPv8Qlg0dIwc/r/IKDW5MRcl9leLtQZUSEkF6KflCy/bKek7Lk1b4sV7pdpTrSd1ZJYovUU7NofjwuxbOxZHXeVZqWmJKP8EUVAD3HaZ/DCIRAlsM1iQp1vo5DuMFLmjkumwe0Zk+8vbKWMBl3Q6AOBN25RJXRnvuYOBCD4itBiE6MI+S3NuWSTbnc7/k2SHU2KANWcTB4A5ymA8D6W3ayumi+c2q6//YxjXDipn2JI8ZAOw3qPqTAq+OWDrkdajNnIrf0+ESjnzU1//S6WDp2e4pxfBnenUsolbtaU9xhjc8dwcZvsv0ems/hBcpjkEWiDXjmnXKNfjVL/o7GzaVdZyjIqv9y4l6KC6db4q906//dqz51cNsgxfLUmPYlPwUVKkfe+vpNlHhYLmJ6qeUQXeI3vQUis9cM=
